export const manufacturers = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "GMC",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Porsche",
  "Ram",
  "Rolls-Royce",
  "Subaru",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
];

export const yearsOfProduction = [
  "2015",
  "2016",
  "2017",
  "2018",
  "2019",
  "2020",
  "2021",
  "2022",
  "2023",
];

export const footerLinks = [
  {
    title: "Menu",
    links: [
      { title: "Home", url: "/" },
      { title: "Catalogue", url: "/" },
      { title: "Services", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "About", url: "/" },
      { title: "Careers", url: "/" },
      { title: "Contact", url: "/" },
    ],
  },
  {
    title: "Further",
    links: [
      { title: "Terms", url: "/" },
      { title: "Privacy", url: "/" },
    ],
  },
  {
    title: "Social media",
    links: [
      {
        title: "Github",
        url: "https://github.com/adrianhajdin?tab=repositories",
        icon: "/github.svg",
      },
      {
        title: "Discord",
        url: "https://discord.gg/KNay9TqYZg",
        icon: "/discord.svg",
      },
      {
        title: "LinkedIn",
        url: "https://www.linkedin.com/company/javascriptmastery/",
        icon: "/linkedin.svg",
      },
    ],
    isSocialMedia: true,
  },
];
