import "./globals.css";

import Footer from "@components/Footer";
import NavBar from "@components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='py-8 lg:px-28 px-4'>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
