import "./globals.css";

import { NavBar, Footer } from "@components";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        {/* <div className='main'>
          <div className='gradient' />
        </div> */}

        {/* <div className='relative z-20'> */}
        <NavBar />
        {children}
        <Footer />
        {/* </div> */}
      </body>
    </html>
  );
}
